parameters:
    symfony.finder.class: Symfony\Component\Finder\Finder
    xsolve_unit_skelgen.path_tools.class: Xsolve\UnitSkelgenBundle\Utils\PathTools
    xsolve_unit_skelgen.name_tools.class: Xsolve\UnitSkelgenBundle\Utils\NameTools
    xsolve_unit_skelgen.class_locator.class: Xsolve\UnitSkelgenBundle\Locator\ClassLocator
    xsolve_unit_skelgen.class_gen_runner.class: Xsolve\UnitSkelgenBundle\Runner\ClassGenerationRunner
    xsolve_unit_skelgen.test_gen_runner.class: Xsolve\UnitSkelgenBundle\Runner\TestGenerationRunner

services:
    symfony.finder:
      class: '%symfony.finder.class%'

    xsolve_unit_skelgen.path_tools:
        class: '%xsolve_unit_skelgen.path_tools.class%'

    xsolve_unit_skelgen.name_tools:
        class: '%xsolve_unit_skelgen.name_tools.class%'
        arguments:
            - "@xsolve_unit_skelgen.path_tools"
            - '%kernel.root_dir%'

    xsolve_unit_skelgen.class_locator:
        class: '%xsolve_unit_skelgen.class_locator.class%'
        arguments:
            - "@symfony.finder"
            - "@xsolve_unit_skelgen.name_tools"
            - "@xsolve_unit_skelgen.path_tools"

    xsolve_unit_skelgen.class_gen_runner:
        class: '%xsolve_unit_skelgen.class_gen_runner.class%'
        arguments:
            - '%xsolve_unit_skelgen.bin%'
            - "@xsolve_unit_skelgen.name_tools"

    xsolve_unit_skelgen.test_gen_runner:
        class: '%xsolve_unit_skelgen.test_gen_runner.class%'
        arguments:
            - '%xsolve_unit_skelgen.bin%'
            - "@xsolve_unit_skelgen.name_tools"
